### ISSUE TITLE
Create Account not working anymore.

### ISSUE THREAD

**Issue by ghost** [marbink/jodel_ios_api#1]
Unfortunately Jodel apparently changed something about their API, so your API doesn't work anymore. I'm sure that I have the correct key, because i extracted it with the "ojoc-keyhack"-Tool out of the newest APK.

(477, {'error': 'Signed request expected', 'metadata': None})
  File "....\jodel_ios_api\jodel_ios_api.py", line 142, in refresh_all_tokens
    raise Exception(resp)
  File "...\jodel_ios_api\jodel_ios_api.py", line 54, in __init__
    r = self.refresh_all_tokens(**kwargs)

**Comment by marbink** [comment]
I don’t know if the secret is the same between iOS and android. I tested my api with the key extracted some hours ago and it works correctly. I made a some modification to hmac generation on my fork. So I have a different code from nborrman’s api. Check diffs and test them on android.

**Comment by ghost** [comment]
I modify you code to the android way and now the api works. 
Thanks for all you work
