### ISSUE TITLE
Jodel has changed their app (android)

### ISSUE THREAD

**Issue by ghost** [marbink/jodel_ios_api#2]
Hello,

Jodel has changed a lot of their app (Android) since their new version. Does the IOS app still work as usual? And if yes, where do you get the decryption key from?

**Comment by marbink** [comment]
Let me check in the weekend. Currently I read the key from iPhone memory when http request is generated.

**Comment by marbink** [comment]
@Telios32 sorry for the delay. I checked now and nothing seems changed. Key is actually starting with "irf" and version is "ios_4.44". Signature payload seems the same too.
I guess I should implement something to export/test these things quickly using my ios app tweak.
Any news on the android side?
