### ISSUE TITLE
"Signed request expected" - new Key?

### ISSUE THREAD

**Issue by wb7** [marbink/jodel_ios_api#3]
Hi,

when creating a new account, `Exception: (477, {u'metadata': None, u'error': u'Signed request expected'})` is raised. How to extract the new secret?

**Comment by marbink** [comment]
I don't think Jodel devs will be happy if I share exactly how to get the key. I usually read it from iPhone memory at runtime, when the HMAC is generated. Study on the web how to hook functions on iOS, there are a lot of ways. In some ways you don't even need the Jailbreak. I have not too much knowledge about RE and I've been able to do it, so it's not so difficult :)
